apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: searxng
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - repoURL: https://charts.searxng.org
      chart: searxng
      targetRevision: "1.0.1"
      helm:
        valueFiles:
          - $values/searxng/values.yaml
    - repoURL: https://github.com/StanleyXie/Universal-Cloud-Platform
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: common-svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
